package com.example.chatapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChatRoomAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatRoomAllPropertiesEquals(ChatRoom expected, ChatRoom actual) {
        assertChatRoomAutoGeneratedPropertiesEquals(expected, actual);
        assertChatRoomAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatRoomAllUpdatablePropertiesEquals(ChatRoom expected, ChatRoom actual) {
        assertChatRoomUpdatableFieldsEquals(expected, actual);
        assertChatRoomUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatRoomAutoGeneratedPropertiesEquals(ChatRoom expected, ChatRoom actual) {
        assertThat(expected)
            .as("Verify ChatRoom auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatRoomUpdatableFieldsEquals(ChatRoom expected, ChatRoom actual) {
        assertThat(expected)
            .as("Verify ChatRoom relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatRoomUpdatableRelationshipsEquals(ChatRoom expected, ChatRoom actual) {
        // empty method
    }
}
